### Database settings
database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: data.sqlite
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: your_schema
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1

#### BEGIN SYNCHRONIZED CONFIGURATION
#### Settings below will be synchronized to all servers.
#### For changes here to take effect, shut down ALL servers in the network, wait for a few seconds, then start ONLY this server.
#### Only start other servers AFTER the "[ModernEcon] Startup completed" message is displayed.
#### Synchronized configuration will always be overridden by the earliest-started server in the network after the last global shutdown (except for some very rare race conditions).

### Core settings
core:
