projects:
  ModernEconomy:
    path: ModernEconomy
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.2
        branch: "4.0"
      - src: SOF3/await-generator/await-generator
        version: ^2.2
