projects:
  ModernEconomy:
    path: ModernEconomy
    projectId: 5114
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.2
      - src: SOF3/await-generator/await-generator
        version: ^2.2
